# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-17 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('title_img', models.CharField(blank=True, max_length=200, verbose_name='文章标题图片')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Article_Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='News')),
                ('order', models.IntegerField(default=0)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Article')),
            ],
            options={
                'verbose_name': '文章内容',
                'verbose_name_plural': '文章内容',
            },
        ),
    ]
