# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-17 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '品牌',
                'verbose_name': '品牌',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('desc', models.CharField(blank=True, max_length=100, verbose_name='商品描述')),
                ('price', models.IntegerField(default=99999, verbose_name='价格')),
                ('img_title', models.ImageField(blank=True, upload_to='Shoes', verbose_name='标题图片')),
                ('img0', models.ImageField(blank=True, upload_to='Shoes', verbose_name='图片一')),
                ('img1', models.ImageField(blank=True, upload_to='', verbose_name='图片二')),
                ('img2', models.ImageField(blank=True, upload_to='', verbose_name='图片三')),
                ('img3', models.ImageField(blank=True, upload_to='', verbose_name='图片四')),
                ('img4', models.ImageField(blank=True, upload_to='', verbose_name='图片五')),
                ('img5', models.ImageField(blank=True, upload_to='', verbose_name='图片六')),
                ('img6', models.ImageField(blank=True, upload_to='', verbose_name='图片七')),
                ('img7', models.ImageField(blank=True, upload_to='', verbose_name='图片八')),
                ('img8', models.ImageField(blank=True, upload_to='', verbose_name='图片九')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shoes.Brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name_plural': '鞋子',
                'verbose_name': '鞋子',
            },
        ),
    ]
